application: my-blog-ccc
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
-  url: /css
   static_dir: css

-  url: /img
   static_dir: img

-  url: /js
   static_dir: js

-  url: /fonts
   static_dir: fonts

-  url: /.*
   script: myblog.app

libraries:
-  name: webapp2
   version: "2.5.2"

-  name: jinja2
   version: "latest"
